### PR TITLE
Project 4: Building with Backgrounds and Gradients

### PR DESCRIPTION
**Pull request by VanessaAoki**
We made a clone of the apple.com homepage, it has different sections of the page; a navbar where we used grid and flexbox, and background image and gradients in the main section. This page is responsive, but works best on a 1024x800 resolution, using the firefox or google chrome browser, assets might look out of place using other browsers or resolutions.

The focus of this branch was to make everything fit in the right places, setting up a good looking website.

### CODE REVIEW

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUIRED :red_circle: 

Hi team :wave: , congratulations on making the apple clone, it looks almost similar to the original one, good work also on the gradient, it looks cool. However, before marking this project as complete, we need to fix two issues

- [x] I have checked your page using the given resolution 1000px by 1000px and i can see a horizontal line meaning your contents are overflowing the given width, kindly fix that

- [x] Align the div section containing site map to float right side of the website.

Thats all :relieved: , kindly submit another review when done, :smile: 
For any queries, dont hesitate to slack me (@peris ndanu)

Regards,
Peris Ndanu

**Comment by VanessaAoki** [comment]
Hello @mimipeshy,

We made all the required changes, and we also made the website responsive.

Kindly request to review our code again, thank you.

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes  ♲

Hi @VanessaAoki and @kamaukk, 👏 You did very well on this project. ✨ Clap  👏  👏  👏 for successfully replicating the apple.com home page. Most requirements have done 👌, Kindly fix the following issues.

[REQUIRED]

- [ ] Fix the spacing and fonts in the footer section. 

footer

_Original_
footer original

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
Abdulaziz Redi Ali

**Comment by kimothokamau** [comment]
We have worked on the suggested changes and submitted a new code review. Kindly review our code/project again.

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### changes required ♻️ 
**Hi @VanessaAoki & @mimipeshy**
Great job so far with the project, but, there are still some changes to be made.

### Required 🔴 
- there is still a horizontal scroll bar, please fix this issue.
- add a little padding to the sides of the footer, like 10px for each side.
---
Please make these changes and submit for another code review.

**Comment by kimothokamau** [comment]
> ### changes required 
> **Hi @VanessaAoki & @mimipeshy**
> Great job so far with the project, but, there are still some changes to be made.
> 
> ### Required 
> * there is still a horizontal scroll bar, please fix this issue.
>which scroll bar, if you are using the live-link to view the project it seems to be delayed to update to match the current repository
> * add a little padding to the sides of the footer, like 10px for each side.
>Done

> Please make these changes and submit for another code review.

**Comment by mimipeshy** [comment]
## STATUS: APPROVED 🎆 🥳  😆 

Hey, team 👋  am very proud of the hard work you guys did, you worked on all the requirements asked. I think the horizontal scrollbar appears because we are testing using a different screen size than the one you are using. In the future please consider sizes 1024px its the standard view of most computers too to avoid all the hustle 😄 

Anyway congratulations, go ahead and merge.  I wish you all the best!!!!

Regards,
Peris Ndanu

**Comment by kimothokamau** [comment]
> ## STATUS: APPROVED   
> Hey, team  am very proud of the hard work you guys did, you worked on all the requirements asked. I think the horizontal scrollbar appears because we are testing using a different screen size than the one you are using. In the future please consider sizes 1024px its the standard view of most computers too to avoid all the hustle 
> 
> Anyway congratulations, go ahead and merge. I wish you all the best!!!!
> 
> Regards,
> Peris Ndanu

Thanks Peris, i just did inspect element, adjusted the browser window and noticed that when I use 1024px the horizontal scrollbar appears. I am using a 1920px screen width so thats why when i'm testing on my side it looks fine. Going forward I will use styling that is responsive for all screen sizes. Thanks again for the valuable feedback

**Pull request merged**
